"use strict";
// lang-pt.ts
Object.defineProperty(exports, "__esModule", { value: true });
exports.LANG_PT_NAME = 'pt';
exports.LANG_PT_TRANS = {
    'hello world': 'Ola mundo',
    'hello greet': 'Ola, %0 %1!',
    'well done': '%0 Bem Vindo',
    'common-msg-success-header': 'Sucesso',
    'common-msg-info-header': 'Informação',
    'common-msg-warn-header': 'Aviso',
    'common-msg-error-header': 'Erro',
    'common-msg-success': 'Execução Ok',
    'common-msg-info': 'Acesso negado',
    'common-msg-warn': 'Erro negocial',
    'common-msg-error': 'Erro interno',
    'login_lb_title': 'título Login',
    'login-lb-user': 'Usuário',
    'login-lb-password': 'Senha',
    'new-simulation': 'Nova Simulação',
    'my-proposals': 'Minhas Propostas',
    'reports': 'Relatórios',
    'support': 'Suporte',
    'login': 'Login',
    'my-profile': 'Perfil',
    'change-password': 'Alteração de senha',
    'field-required': 'Campo Obrigatório! (mínimo 6 caracteres)',
    'current-password': 'Senha Atual',
    'new-password': 'Nova Senha',
    'repeat-password': 'Repita Nova Senha',
    'notifications': 'Notificações',
    'change-brand': 'Trocar Marca',
    'edit': 'Editar',
    'save': 'Salvar',
    'clear': 'Limpar',
    'forgot-password': 'Esqueci minha senha',
    'forgot-password-lb-useremail': 'Usuário/e-mail',
    'forgot-password-msg': 'Informe seu usuário ou endereço de e-mail para estar recebendo um e-mail com o link pra criar a nova senha',
    //Tela de Notícias adm
    'save-news': 'Salvar Notícia',
    //Nova Inserção
    'search': 'Procurar',
    'reset': 'Redefinir',
    'enter': 'Entrar',
    'proposal-number': 'Número da Proposta',
    'customer-type': 'Tipo Cliente',
    'logout': 'Sair',
    'send': 'Enviar',
    //Formulário Cliente
    'custumer-personal-data': 'DADOS PESSOAIS DO CLIENTE',
    'cpf-cnpj': 'CPF ou CNPJ',
    'client-name': 'Nome do Cliente',
    'contact-information': 'Dados de Contato',
    'phone-number': 'Telefone do Cliente',
    'localization': 'Localização',
    'state': 'Estado',
    'select-state': 'Selecione um Estado',
    'simulation-information': 'Informações de Simulação',
    'direct-sale': 'Venda Direta',
    'new-ones': 'Seminovos',
    'sale-type': 'Tipo de Venda',
    'choose-vehicle': 'Escolher Veículo',
    'brands': 'Marcas',
    'simulate': 'Simular',
    'model': 'Modelo',
    'required-field': 'campo obrigatório'
};
//# sourceMappingURL=lang-pt.js.map